project_id = "vawouugtzwmejxqkeqqj"

[functions.xmrig-direct-proxy]
verify_jwt = false

[functions.supportxmr-proxy]
verify_jwt = false

[functions.record-battery-data]
verify_jwt = false

[functions.monitor-device-connections]
verify_jwt = false

[functions.issue-engagement-command]
verify_jwt = false

[functions.validate-pop-event]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.aggregate-device-metrics]
verify_jwt = false

[functions.ai-battery-optimizer]
verify_jwt = false

[functions.award-xmrt-tokens]
verify_jwt = false

[functions.ingest-mining-data]
verify_jwt = false

[functions.associate-device-miner]
verify_jwt = false

[functions.update-payout-wallet]
verify_jwt = false
